### ISSUE TITLE
[Request] AutoLoad Scripts

### ISSUE THREAD

**Issue by QuasarX** [jaakkytt/InjectCode#2]
Please add autoload scripts feature for selected pages.

**Comment by jaakkytt** [comment]
Hey, please describe a bit more the functionality you are looking for and if possible give an example usage scenario. Currently having trouble understanding what exactly do you have in mind :)

**Comment by QuasarX** [comment]
My Code;

```
if (window.location.href.match('\\google')) {
    window.alert("Google Opened");
} 
```

This code auto loading all pages. You can add feature; "run code only these pages" option.

**Comment by jaakkytt** [comment]
Ah, I see. As you are essentially requesting the same feature as was https://github.com/jaakkytt/InjectCode/issues/1 I am closing this issue here. I have some parts of it written but nothing close to full implementation. Please see https://github.com/jaakkytt/InjectCode/issues/1 and the "temporary" solution I offered there, in your case:

```
testLocation('google.com', function () {
    window.alert('Google opened');
});
```

Sadly can't make any promises to when I get to implementing this feature as of today.
